### PR TITLE
Fix dragging marker with offset

### LINKED ISSUE #691: Marker is jumping at start of drag and only works with offset
I'm having trouble with dragging with an offset. At the start of drag the marker jumps up and to the left. Oddly enough, when I remove the offsets now, the marker isn't dragging at all.
```javascript
<ReactMapGL
  ref={map => (this.mapRef = map)}
  {...viewport}
  mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN}
  onViewportChange={viewport => this.setState({ viewport })}
>
  <Marker
    latitude={marker.latitude}
    longitude={marker.longitude}
    offsetLeft={-10}
    offsetTop={-25}
    draggable
    onDragEnd={this.onMarkerDragEnd}
  >
    <img
      width="20px"
      height="25px"
      src="https://image.flaticon.com/icons/svg/33/33622.svg"
    />
  </Marker>
</ReactMapGL>
```

why

If it matters, this is embedded in an electron app, but that really shouldn't from my knowledge of electron.

Thanks!

### PR DESCRIPTION
**Pull request by schnerd**
Fixes #691 

Think I overlooked this initially because the `<Pin>` component used in examples uses custom `translate` rules instead of the Marker offset props. I've updated the example and fixed the root issue.

### CODE REVIEW

File: examples/draggable-markers/src/control-panel.js [hunk 1]
```diff
@@ -26,9 +26,9 @@ export default class ControlPanel extends PureComponent {
       <Container>
         <h3>Draggable Marker</h3>
         <p>Try dragging the marker to another location.</p>
-        <p>
+        <div>
           {eventNames.map(this.renderEvent)}
-        </p>
+        </div>
```
Comment (schnerd) [inline examples/draggable-markers/src/control-panel.js]: Fixes a couple react warnings in the example

File: src/components/draggable-control.js [hunk 2]
```diff
@@ -20,17 +20,26 @@
...
 const propTypes = Object.assign({}, BaseControl.propTypes, {
   draggable: PropTypes.bool,
   onDrag: PropTypes.func,
   onDragEnd: PropTypes.func,
-  onDragStart: PropTypes.func
+  onDragStart: PropTypes.func,
+  // Offset from the left
+  offsetLeft: PropTypes.number,
+  // Offset from the top
+  offsetTop: PropTypes.number
```
Comment (schnerd) [inline src/components/draggable-control.js]: Moving the `offset*` props back into draggable control felt better than overriding _getDragLngLat in Marker. If there are other classes extending DraggableControl in the future, they may also want to support offsets.

File: src/components/marker.js [hunk 3]
```diff
@@ -58,18 +49,33 @@ export default class Marker extends DraggableControl {
...
+
+    const [x, y] = this._getPosition();
 
     const containerStyle = {
       position: 'absolute',
-      left: x + offsetLeft,
-      top: y + offsetTop
+      left: x,
+      top: y,
+      cursor: draggable ? (dragPos ? 'grabbing' : 'grab') : 'auto'
```
Comment (schnerd) [inline src/components/marker.js]: @Pessimistress This isn't perfect because sometimes the mouse moves faster than the marker, but it seems to work reasonably well. Let me know if you there's a better way of achieving this.

**Comment by schnerd** [comment]
Not sure why `/travis-ci/push` failed... tests seem unrelated to my changes.

File: src/components/marker.js (hunk 3 above)
Comment (Pessimistress) [reply src/components/marker.js]: You can set the cursor style on the entire canvas to fix this. Without doing it the "React way" you can access the root element through the pointer events...

Comment (schnerd) [reply src/components/marker.js]: Gotcha. Sounds like something that might require its own PR, and the small change here should be a decent improvement for now.

**Comment by timendez** [comment]
@schnerd just FYI the example on the page still allows you to move the pin if you click and hold to the bottom left of the pin:

gif

**Comment by Pessimistress** [comment]
@schnerd https://github.com/uber/react-map-gl/blob/master/docs/developer-guide.md#website
